name: frontend_flutter
description: A simple Flutter app to test FastAPI backend
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
